Merge container images
Now there is a single container image that generates both linux and
win32 toolchains. This requires using volumes when running `docker run`
cmd

diff --git a/build-docker b/build-docker
--- a/build-docker
+++ b/build-docker
@@ -1,8 +1,6 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-docker buildx build -f docker/Dockerfile.linux -t tricore-linux-builder . || { echo "Error while building linux toolchain container"; exit 1; }
-docker buildx build -f docker/Dockerfile.mingw -t tricore-mingw-builder . || { echo "Error while building mingw toolchain container"; exit 1; }
-echo "Exporting compiler in tricore-gcc-11.3.1-linux.zip..."
-docker run --rm tricore-linux-builder > tricore-gcc-11.3.1-linux.zip
-echo "Exporting compiler in tricore-gcc-11.3.1-mingw.zip..."
-docker run --rm tricore-mingw-builder > tricore-gcc-11.3.1-mingw.zip
+docker build --no-cache -f docker/Dockerfile -t tricore-builder . || { echo "Error while building mingw toolchain"; exit 1; }
+echo "Exporting compiler distributables..."
+mkdir -p out
+docker run --rm -v $(pwd)/out:/output tricore-builder
